        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 28 11:50:10 2011
        MODULE CLOSE_FILE__genmod
          INTERFACE 
            SUBROUTINE CLOSE_FILE
            END SUBROUTINE CLOSE_FILE
          END INTERFACE 
        END MODULE CLOSE_FILE__genmod
