        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 28 11:50:09 2011
        MODULE GETCOORDINATES__genmod
          INTERFACE 
            SUBROUTINE GETCOORDINATES(ANX,AY,AZ,I)
              REAL(KIND=8) :: ANX
              REAL(KIND=8) :: AY
              REAL(KIND=8) :: AZ
              INTEGER(KIND=4) :: I
            END SUBROUTINE GETCOORDINATES
          END INTERFACE 
        END MODULE GETCOORDINATES__genmod
