        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 28 11:50:09 2011
        MODULE GETNODENUMBER__genmod
          INTERFACE 
            SUBROUTINE GETNODENUMBER(NODENUM,IELEM,INODE)
              INTEGER(KIND=4) :: NODENUM
              INTEGER(KIND=4) :: IELEM
              INTEGER(KIND=4) :: INODE
            END SUBROUTINE GETNODENUMBER
          END INTERFACE 
        END MODULE GETNODENUMBER__genmod
