        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 28 11:50:09 2011
        MODULE GETSPECPRESNODENUMBER__genmod
          INTERFACE 
            SUBROUTINE GETSPECPRESNODENUMBER(NODEINDEX,NODENUMBER,      &
     &SPECPRESS,CONC)
              INTEGER(KIND=4) :: NODEINDEX
              INTEGER(KIND=4) :: NODENUMBER
              REAL(KIND=8) :: SPECPRESS
              REAL(KIND=8) :: CONC
            END SUBROUTINE GETSPECPRESNODENUMBER
          END INTERFACE 
        END MODULE GETSPECPRESNODENUMBER__genmod
