        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 28 11:50:09 2011
        MODULE GETSPECCONCNODENUMBER__genmod
          INTERFACE 
            SUBROUTINE GETSPECCONCNODENUMBER(NODEINDEX,NODENUMBER,CONC)
              INTEGER(KIND=4) :: NODEINDEX
              INTEGER(KIND=4) :: NODENUMBER
              REAL(KIND=8) :: CONC
            END SUBROUTINE GETSPECCONCNODENUMBER
          END INTERFACE 
        END MODULE GETSPECCONCNODENUMBER__genmod
