        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 28 11:50:10 2011
        MODULE INDAT0__genmod
          INTERFACE 
            SUBROUTINE INDAT0
            END SUBROUTINE INDAT0
          END INTERFACE 
        END MODULE INDAT0__genmod
