        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 28 11:50:11 2011
        MODULE INITIALIZE__genmod
          INTERFACE 
            SUBROUTINE INITIALIZE(NUMNODES,NUMELEM,NPRESB,NCONCB,       &
     &IERRORCODE,INPUTFILE)
              INTEGER(KIND=4) :: NUMNODES
              INTEGER(KIND=4) :: NUMELEM
              INTEGER(KIND=4) :: NPRESB
              INTEGER(KIND=4) :: NCONCB
              INTEGER(KIND=4) :: IERRORCODE
              CHARACTER(*), INTENT(IN) :: INPUTFILE
            END SUBROUTINE INITIALIZE
          END INTERFACE 
        END MODULE INITIALIZE__genmod
