        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 28 11:50:08 2011
        MODULE XERCNT__genmod
          INTERFACE 
            SUBROUTINE XERCNT(LIBRAR,SUBROU,MESSG,NERR,LEVEL,KONTRL)
              CHARACTER(*) :: LIBRAR
              CHARACTER(*) :: SUBROU
              CHARACTER(*) :: MESSG
              INTEGER(KIND=4) :: NERR
              INTEGER(KIND=4) :: LEVEL
              INTEGER(KIND=4) :: KONTRL
            END SUBROUTINE XERCNT
          END INTERFACE 
        END MODULE XERCNT__genmod
