        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 28 11:50:08 2011
        MODULE XERHLT__genmod
          INTERFACE 
            SUBROUTINE XERHLT(MESSG)
              CHARACTER(*) :: MESSG
            END SUBROUTINE XERHLT
          END INTERFACE 
        END MODULE XERHLT__genmod
