        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 28 11:50:08 2011
        MODULE XERPRN__genmod
          INTERFACE 
            SUBROUTINE XERPRN(PREFIX,NPREF,MESSG,NWRAP)
              CHARACTER(*) :: PREFIX
              INTEGER(KIND=4) :: NPREF
              CHARACTER(*) :: MESSG
              INTEGER(KIND=4) :: NWRAP
            END SUBROUTINE XERPRN
          END INTERFACE 
        END MODULE XERPRN__genmod
