        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 28 11:50:08 2011
        MODULE XGETUA__genmod
          INTERFACE 
            SUBROUTINE XGETUA(IUNITA,N)
              INTEGER(KIND=4) :: IUNITA(5)
              INTEGER(KIND=4) :: N
            END SUBROUTINE XGETUA
          END INTERFACE 
        END MODULE XGETUA__genmod
